package drawbridge

var DRAWBRIDGE_AND_EMISSARY_SIGNING_PUBKEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZdmFkxYJKwYBBAHaRw8BAQdAm2POyMUlUuFJyH00zVHKsaoHk3jpebsmvmkm
LmEldkW0I0RyYXdicmlkZ2UgYW5kIEVtaXNzYXJ5IFNpZ25pbmcgS2V5iJAEExYI
ADgWIQTZ1aiaA26m1gOUsSpEpNMvoA+NOQUCZdmFkwIbAwULCQgHAgYVCgkICwIE
FgIDAQIeAQIXgAAKCRBEpNMvoA+NOR2pAP95VoAruA/46FW0rg+qEyhZdEf+kBlu
hJ4NBdqjRUzJhgD/TD89ca4eDgt/FZN45U34iwjYAbu3zbQtsqoI9wRL9A8=
=Pj8O
-----END PGP PUBLIC KEY BLOCK-----`
