// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func GetOnboardingModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"modal\" _=\"on closeModal add .closing then wait for animationend then remove me\"><div class=\"modal-underlay\"></div><form class=\"modal-content\" hx-post=\"/admin/post/config\" hx-target=\"#listener-address\"><h2>Set Up Drawbridge</h2><label for=\"listener-address\">What IP should Drawbridge be accessible from?</label><p class=\"note-text\">Note: this is the address your Emissary clients will use to connect to Drawbridge. It can be your LAN (local) or WAN (accessible outside your network) address.</p><input name=\"listener-address\" type=\"text\" id=\"listener-address\" placeholder=\"50.42.165.84\"> <label for=\"enable-ping\"><input type=\"checkbox\" id=\"enable-ping\" name=\"enable-ping\" checked> Automatically send anonymous and private daily usage ping to Dawson to estimate acive users. </label><p class=\"note-text\">Note: this feature does not collect your IP address.</p><input name=\"submit-config\" type=\"submit\" id=\"submit-config\" _=\"on click trigger closeModal\"></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
